name: SPCI

on: [push]

jobs:
  sast_scan:
    name: Bandit security scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . bandit-report.json
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Bandit findings
        path: bandit-report.json
      
